### ISSUE TITLE
SpellCheckerに関して

### ISSUE THREAD

**Issue by ochairo** [LeftLetter/react-template-spa#1]
# Discussion

英語のスペルチェックを自動化して、気付きやすくしたいので下記追加した方が良いと思います。
- [VS code Extension](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

Checkを回避してほしい一般的な日本語などの設定ファイルも追加した方が良いと思います。
また、プロジェクトで使用する固有名詞なども追加できるので、その辺はプロジェクトに任せれば良いかと思います。

## 例：
![image](https://user-images.githubusercontent.com/19258508/235117122-b181a1c1-0c78-46f0-bb34-6c727bf9b5f3.png)

![image](https://user-images.githubusercontent.com/19258508/235117210-1f7d83f9-fc2c-459d-9f42-267186496b57.png)

**Comment by ochairo** [comment]
@LeftLetter 
PR出したいのですが、権限頂けますでしょうか？

https://docs.github.com/ja/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

**Comment by LeftLetter** [comment]
@andres-oshiro 
ありがとうございます！ぜひ入れておきたいですね。
コラボレーターに追加したので多分できると思います。
